export const LOAD_STAR_WARS_API = 'LOAD_STAR_WARS_API';
export const LOAD_PLANET_NAME = 'LOAD_PLANET_NAME';

export const LOADING_STARWATS_ON = 'LOADING_STARWATS_ON';
export const LOADING_STARWATS_OFF = 'LOADING_STARWATS_OFF';
